image: Visual Studio 2019
configuration: Release
platform: Any CPU

cache:
  - '%TEMP%\SQL2019' -> appveyor.yml

before_build:
  - nuget restore
  - dotnet restore

build:
  verbosity: minimal
  project: Cogito.SqlServer.Deployment.sln

before_test:
  - ps: |-
      mkdir "$env:TEMP\SQL2019" | Out-Null
      if (!(Test-Path "$env:TEMP\SQL2019-SSEI-Dev.exe")) {
        Invoke-WebRequest -Uri "https://download.microsoft.com/download/b/8/c/b8ce1000-2e0b-4bc8-b4e4-646e9a439525/SQL2019-SSEI-Dev.exe" -OutFile "$env:TEMP\SQL2019-SSEI-Dev.exe" | Out-Null
      }
      if (!(Test-Path "$env:TEMP\SQL2019\SQLServer2019-DEV-x64-ENU.exe")) {
        & "$env:TEMP\SQL2019-SSEI-Dev.exe" /Quiet /Action=Download /MediaType=CAB /MediaPath="$env:TEMP\SQL2019" | Out-Null
      }
      if (!(Test-Path "$env:TEMP\SQL2019\media\setup.exe"))
          & "$env:TEMP\SQL2019\SQLServer2019-DEV-x64-ENU.exe" /q /x:"$env:TEMP\SQL2019\media" | Out-Null
      }
  - ps: |-
      $p = Resolve-Path 'Cogito.SqlServer.Deployment.runsettings'
      $x = Select-Xml -Path $p -XPath '//RunSettings/TestRunParameters/Parameter[@name="SqlSetupExePath"]'
      $x.Node.value = "$env:TEMP\SQL2019\media\setup.exe"
      $x.Node.OwnerDocument.Save($p)

test_script:
  - cmd: vstest.console /logger:Appveyor /settings:Cogito.SqlServer.Deployment.runsettings "Cogito.SqlServer.Deployment.Tests\bin\Release\net47\Cogito.SqlServer.Deployment.Tests.dll"
  - cmd: vstest.console /logger:Appveyor /settings:Cogito.SqlServer.Deployment.runsettings "Cogito.SqlServer.Deployment.Tests\bin\Release\netcoreapp3.1\Cogito.SqlServer.Deployment.Tests.dll"

artifacts:
  - path: pkg\*.nupkg
    name: Cogito.SqlServer.Deployment

deploy:
  provider: NuGet
  server: https://nuget.pkg.github.com/wasabii/index.json
  username: wasabii
  api_key:
    secure: xrFuWmVqekabWUvYce7mOmKS4ToqdtFJOGgiLYyrDRVZJhMSMvpOUVxf0mhzwGiH
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
