image: Visual Studio 2019
configuration: Release
platform: Any CPU

before_build:
  - nuget restore
  - dotnet restore

build:
  verbosity: minimal
  project: Cogito.SqlServer.Deployment.sln

artifacts:
  - path: pkg\*.nupkg
    name: Cogito.SqlServer.Deployment

deploy:
  provider: NuGet
  server: https://nuget.pkg.github.com/wasabii/index.json
  username: wasabii
  api_key:
    secure: xrFuWmVqekabWUvYce7mOmKS4ToqdtFJOGgiLYyrDRVZJhMSMvpOUVxf0mhzwGiH
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
