image: Visual Studio 2019
configuration: Release
platform: Any CPU

before_build:
  - nuget restore
  - dotnet restore

install:
  - cmd: appveyor DownloadFile https://download.microsoft.com/download/b/8/c/b8ce1000-2e0b-4bc8-b4e4-646e9a439525/SQL2019-SSEI-Dev.exe
  - cmd: mkdir %CD%\SQL2019
  - cmd: .\SQL2019-SSEI-Dev.exe /IAcceptSqlServerLicenseTerms /Quiet /Action=Download /MediaType=CAB /MediaPath=%CD%\SQL2019

build:
  verbosity: minimal
  project: Cogito.SqlServer.Deployment.sln

artifacts:
  - path: pkg\*.nupkg
    name: Cogito.SqlServer.Deployment

deploy:
  provider: NuGet
  server: https://nuget.pkg.github.com/wasabii/index.json
  username: wasabii
  api_key:
    secure: xrFuWmVqekabWUvYce7mOmKS4ToqdtFJOGgiLYyrDRVZJhMSMvpOUVxf0mhzwGiH
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
